import gql from 'graphql-tag';

export default gql`
  subscription($groupId: ID!) {
    post(where: { node: { group: { id: $groupId} } } ) {
      node{
        id
        createdAt
        content
        files {
          id
          url
        }
      }
    }
  }
`

