import gql from 'graphql-tag';

export default gql`
  query($id: ID!){
    group(where: { id: $id }) {
      id
      name
      posts(orderBy: createdAt_ASC) {
        id
        createdAt
        content
        files {
          id
          url
        }
      }
    }
  }
`

